# Generated by Django 5.0.4 on 2024-04-19 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('payment', '지급결재함'), ('collection', '집금결재함'), ('alarm', '알람')], max_length=20, verbose_name='알림 종류')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='카운트 수')),
            ],
            options={
                'verbose_name': '알림',
                'verbose_name_plural': '알림',
            },
        ),
    ]
